<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Description>Rsa license package</Description>
    <Copyright>2025</Copyright>
    <PackageIcon>yellow-E (1).png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\Downloads\yellow-E (1).png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="9.0.4" />
  </ItemGroup>

</Project>
